### ISSUE TITLE
No index.html file

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/matlab-novice-capstone-biomed#2]
This repo does not have an index.html file in it's gh-pages branch, so when people go to http://swcarpentry.github.io/capstone-biomedical-engineering/ they get a 404.

**Comment by IsaKiko** [comment]
Thanks, good point. 
Do you think the lesson itself is short enough to make it the index.html or does it need an additional one?
Also, it's being liked to on the lesson page, so @gvwilson needs to be in the loop for this.

**Comment by wking** [comment]
On Mon, Apr 20, 2015 at 02:57:40PM -0700, Matt Davis wrote:

> This repo does not have an index.html file in it's gh-pages branch…

Who needs an index.html when you can _fly a quadcopter with your
brain!!_ ?

;)

**Comment by IsaKiko** [comment]
PR here:
https://github.com/swcarpentry/capstone-biomedical-engineering/pull/3

**Comment by jiffyclub** [comment]
Some other cleanup topics for this repo:
- there's no README
- it's not clear this is a Matlab lesson

Maybe it's time to apply a naming convention to the capstone lessons, like maybe matlab-novice-capstone-biomed? I know that's getting a bit long, but it's already a bit long.

**Comment by DamienIrving** [comment]
Soon @sritchie73 will be working on a similar biomedical capstone using R instead of MATLAB, so adding the language to the naming convention is probably a good idea.

**Comment by IsaKiko** [comment]
@jiffyclub I added a readme (same PR), but I don't know how to change the repo name.

**Comment by jiffyclub** [comment]
I can change the name if everyone likes my suggestion.

**Comment by IsaKiko** [comment]
@jiffyclub I'm happy with it. Thank you! 
Could you or @gvwilson also make sure the link on http://software-carpentry.org/lessons.html gets updated?

**Comment by jiffyclub** [comment]
Yup, see https://github.com/swcarpentry/site/pull/949.
